---
- name:  containerd config init
  hosts: all
  become: yes
  tasks:
  - name: create containerd config directory
    file:
      path: /etc/containerd 
      state: directory
      mode: 0755
      group: root
      owner: root
      
  - name: import default config
    shell: | 
      containerd config default > /etc/containerd/config.toml
    args:
      creates: /etc/containerd/config.toml
  
  - name: set SystemdCgroup true
    replace:
      path: /etc/containerd/config.toml
      regexp: "^(\\s*SystemdCgroup\\s*=\\s*).*"
      replace: \1true
  
  - name: set pause images url
    replace:
      path: /etc/containerd/config.toml
      regexp: "registry.k8s.io/pause:3.10.1"
      replace: registry.aliyuncs.com/google_containers
    

  - name: start containerd
    systemd:
      name: containerd
      state: startd
      enabled: true