---
k8s_packages:
- runc_1.3.4-0ubuntu1~24.04.1_amd64.deb
- libipset13_7.19-1ubuntu2_amd64.deb
- kubernetes-cni_1.7.1-1.1_amd64.deb
- containerd_2.2.1-0ubuntu1~24.04.2_amd64.deb
- kubelet_1.34.8-1.1_amd64.deb  
- ipset_7.19-1ubuntu2_amd64.deb
- ipvsadm_1%3a1.31-1ubuntu0.1_amd64.deb


k8s_controll_packages:
- kubeadm
- kubectl
- kubelet
- containerd
- ipset
- ipvsadm      
